<?php

/**
 * ProcessWire Autolinks Textformatter
 *
 * This is a commercially supported module, please do not distribute. 
 * Part of the ProFields package 
 * 
 * Copyright (C) 2014 by Ryan Cramer 
 * 
 * http://processwire.com
 *
 *
 */

class TextformatterAutoLinks extends Textformatter implements ConfigurableModule {

	public static function getModuleInfo() {
		return array(
			'title' => __('ProFields: Auto Links', __FILE__), 
			'summary' => __('Automatically links any of the configured text phrases to a URL, any time they appear.', __FILE__), 
			'version' => 2, 
			'url' => "http://processwire.com", 
		); 
	}

	/**
	 * Default max number of times to link a term within the same field
	 *
	 */
	const defaultTermLimit = 5; 

	/**
	 * Default max number of links to generate in any block of text
	 *
	 */
	const defaultMaxLinks = 20; 

	/**
	 * Default distance between words (in characters) before re-linking the same term again.
	 *
	 */
	const defaultDistance = 100; 

	/**
	 * Default allowed tags to link within (blank=any)
	 *
	 */
	const defaultAllowTags = '';

	/**
	 * Default markup for internal links
	 *
	 */
	const defaultLinkMarkup = '<a href="{href}">{text}</a>'; 

	/**
	 * Default markup for external links
	 *
	 */
	const defaultLinkMarkupExt = '<a target="_blank" href="{href}">{text}</a>'; 

	/**
	 * Associative array of term => URL
	 *
	 */
	protected $terms = array();

	/**
	 * Temporary holding string for terms
	 *
	 * This is populated by module configuration, and later moved to $terms array
	 * once we know for certain that it will actually be used. 
	 *
	 */
	protected $termsStr = null;

	/**
	 * Language ID that terms are for
	 *
	 * Used only if multi-language support is active
	 *
	 */
	protected $languageID = 0;

	/**
	 * Other/future configuration data
	 *
	 */
	protected $data = array(
		'termLimit' => 0, // max number of times to link a term in a block of copy
		'maxLinks' => 0, // max number of linked terms allowed in a block of copy
		'distance' => 0,  // distance between the same tags
		'allowTags' => '', // tags that we're allowed to produce links within (blank=any)
		'linkMarkup' => '', // internal link markup
		'linkMarkupExt' => '', // external link markup
		);


	/**
	 * Initialize the Textformatter
	 *
	 */
	public function init() {
		// pick up terms defined in $config variable, optional
		$terms = $this->wire('config')->TextformatterAutolinks;
		if(is_array($terms)) $this->terms = array_merge($terms, $this->terms); 
		if(empty($this->data['linkMarkup'])) $this->data['linkMarkup'] = self::defaultLinkMarkup;
		if(empty($this->data['linkMarkupExt'])) $this->data['linkMarkupExt'] = self::defaultLinkMarkupExt;
	}

	/**
	 * Convert $this->termsStr into array in $this->terms
	 *
	 */
	protected function processTermsStr() {

		if(is_null($this->termsStr)) return;

		$value = explode("\n", $this->termsStr); 

		foreach($value as $line) {
			if(strpos($line, '=') === false) continue; 
			list($term, $url) = explode('=', $line); 
			$this->terms[trim($term)] = trim($url); 
		}

		$this->termsStr = null;
	}

	/**
	 * Setup terms for the user's language
	 *
	 */
	protected function setupLanguage() {
		
		$language = $this->wire('user')->language; 
		if(!$language || !$language->id) return; // languages not active

		if($this->languageID && $language->id == $this->languageID) return; // already have the right terms language

		// language terms not yet processed or not consistent with user's language
		$termsStr = $this->get("terms$language"); // get language-specific terms
		if($termsStr) { 
			// if terms are defined for this language, replace the current terms with them
			$this->terms = array(); // clear out existing terms
			$this->termsStr = $termsStr; // queue new terms to be processed (by processTermsStr) 
		}
		$this->languageID = $language->id; // remember that this language is active
	}

	/**
	 * Populate autolinks
	 *
	 */
	public function formatValue(Page $page, Field $field, &$value) {

		if(!strlen($value)) return; 
		if($this->wire('languages')) $this->setupLanguage();
		if(!is_null($this->termsStr)) $this->processTermsStr();
		$termLimit = $this->data['termLimit']; 
		if(!$termLimit) $termLimit = self::defaultTermLimit; 
		$rootURL = $this->wire('config')->urls->root; 
		$currentPage = $this->wire('page'); // page being viewed (which may be different from $page)
		$maxLinkedTerms = (int) $this->maxLinks; 
		$numLinkedTerms = 0; 

		foreach($this->terms as $term => $url) {

			// avoid linking page if we are already on it
			if($url == $currentPage->path() || $url == $currentPage->id) continue; 

			// make path-based URLs relative to root
			if(substr($url, 0, 1) == '/' && $rootURL != '/') $url = $rootURL . substr($url, 1); 

			// format the term
			if($this->formatTerm($value, $term, $url, $termLimit)) $numLinkedTerms++;
			
			// abort if we've gone over the max allowed links
			if($maxLinkedTerms > 0 && $numLinkedTerms >= $maxLinkedTerms) break;
		}

	}

	/**
	 * Check if $termPos exists within the boundaries (in $str) of an allowed tag
	 *
	 * @param string $str
	 * @param int $termPos
	 * @return bool
	 *
	 */
	protected function inAllowedTag(&$str, $termPos) {

		$in = false; 
		static $allowTags = array();

		if(!count($allowTags)) $allowTags = explode(' ', $this->allowTags); 
		
		foreach($allowTags as $tag) {
		
			$closePos = mb_stripos($str, "</$tag>", $termPos); 
			if($closePos === false) continue; // if no closing tag present, skip

			$startPos = mb_stripos($str, "<$tag>", $termPos); 
			if($startPos === false || $startPos > $closePos) {
				// start tag isn't here (meaning it comes before our term), or it comes sometime after
				// this is good, as it means our term is likely within an allowed tag, however, we 
				// need to double check now with an attribute version of the tag
				$startPos = mb_stripos($str, "<$tag ", $termPos); 
				if($startPos === false || $startPos > $closePos) {
					// if we made it here, then we are within an allowed tag
					$in = true; 
					break;
				}
			}
		}

		return $in;
	}

	/**
	 * Find and populate a single term
	 *
	 * @param string $str
	 * @param string $term
	 * @param string $url
	 * @param int $limit
	 * @return int Number of links generated by this method call
	 *
	 */
	protected function formatTerm(&$str, $term, $url, $limit) {

		$startPos = 0; 
		$cnt = 0; 
		$_term = $term;
		$termLength = mb_strlen($term); 
		$distance = (int) $this->data['distance'];
		$n = 0;
		$maxN = 255; 

		do { 
			if($startPos && mb_strlen($str) <= $startPos) break;

			$term = $_term; // restore original

			$termPos = mb_stripos($str, $term, $startPos); 
			if($termPos === false) break; 

			$startPos = $termPos + $termLength;

			// determine if we are within an allowed tag
			if($this->allowTags && !$this->inAllowedTag($str, $termPos)) continue; 

			// determine if the block of text is already linked
			$closeLinkPos = mb_stripos($str, '</a>', $termPos); 
			if($closeLinkPos !== false) {
				// $str contains a closing link ahead, make sure it comes after an opening link
				$openLinkPos = mb_stripos($str, '<a ', $termPos); 
				if(!$openLinkPos || $openLinkPos > $closeLinkPos) {
					// term is already surrounded in a link
					continue; 
				}
			}

			// determine if we are in an attribute of another tag
			$endTagPos = mb_strpos($str, '>', $termPos); 
			if($endTagPos !== false) {
				$startTagPos = mb_strpos($str, '<', $termPos); 
				if(!$startTagPos || $startTagPos > $endTagPos) {
					// term may be within a tag, like an <img alt='...'>
					continue; 
				}
			}

			if(ctype_digit("$url")) {
				// URL specified as a page ID number
				$page = $this->wire('pages')->get((int) $url); 			
				if(!$page->id || $page->id == $this->wire('page')->id || !$page->viewable()) continue; 
				$url = $page->url;
			}

			$str1 = mb_substr($str, 0, $termPos); // part before the term
			$str2 = mb_substr($str, $startPos); // part after the term
			$term = mb_substr($str, $termPos, $termLength); // actual term in context

			// check to ensure that the term is a complete term and not a component of some other word
			$charBeforeTerm = mb_substr($str, $termPos-1, 1); 
			$charAfterTerm = mb_substr($str2, 0, 1); 

			$ok = true;
			foreach(array($charBeforeTerm, $charAfterTerm) as $test) {
				if(!strlen($test) || ctype_space($test) || ctype_punct($test)) continue; // these are ok
				if(ctype_print($test) || ctype_alnum($test)) $ok = false;
				if(!$ok) break;
			}

			// if term is not ok, we'll skip it since it's a component of some other term
			if($ok) {
				// insert the link
				$link = strpos($url, '://') !== false ? $this->linkMarkupExt : $this->linkMarkup; 
				$link = str_replace(array('{href}', '{text}'), array($url, $term), $link); 
				$str = $str1 . $link . $str2; 
				$startPos += (mb_strlen($link) - $termLength) + $distance;
				$cnt++;
			}


		} while($termPos > 0 && $cnt < $limit && ++$n <= $maxN); 

		return $cnt; 
	}

	/**
	 * Set configuration value, for ConfigurableModule interface
	 *
	 */
	public function set($key, $value) {

		if($key == 'terms') {
			if(is_string($value)) $this->termsStr = $value; 
				else if(is_array($value)) $this->terms = $value; 
		} else {
			$this->data[$key] = $value;
		}

		return $this; 
	}

	/**
	 * Get configuration value for ConfigurableModule interface
	 *
	 */
	public function get($key) {

		if($key == 'terms') {
			if(strlen($this->termsStr)) {
				$value = $this->termsStr; 
			} else { 
				// convert array back to text, for config and storage
				$value = '';
				foreach($this->terms as $term => $url) {
					$value .= "$term=$url\n";
				}
				$value = trim($value); 
			}

		} else if(isset($this->data[$key])) {
			// some other/future config value
			$value = $this->data[$key]; 

		} else {
			// api variable
			$value = $this->wire($key);
		}

		return $value; 
	}

	public function __set($key, $value) {
		return $this->set($key, $value); 
	}

	public function __get($key) { 
		return $this->get($key); 
	}

	/**
	 * Get Inputfields for configuration of the module
	 *
	 */
	public static function getModuleConfigInputfields(array $data) {
		$inputfields = new InputfieldWrapper();

		$f = wire('modules')->get('InputfieldTextarea'); 		
		$f->attr('name', 'terms');
		$f->attr('value', isset($data['terms']) ? $data['terms'] : ''); 
		$f->label = __('Terms to Link'); 
		$f->description = __('Enter one per line of: "term=URL", where "term" is the text/phrase you want to automatically link, and "URL" is the URL/path you want it to link to. If your ProcessWire installation runs from a subdirectory, do not include that in the path as it will be prepended automatically. You may also specify a page ID (number) for the URL to determine it automatically at runtime.'); // Terms description
		$f->notes = __('Example: Hello World=/hello/world/'); // Terms example
		$f->notes .= "\n" . __('Term text is not case sensitive. If preferred, terms may also be specified manually via $config->TextformatterAutolinks = array("term" => "URL"); in your /site/config.php file.'); // Terms notes
		$f->rows = 15; 
		$inputfields->add($f); 

		$languages = wire('languages'); 
		if($languages) {
			// language-specific terms
			$defaultLabel = $f->label; 
			$defaultField = $f; 
			foreach($languages as $language) {
				$label = $defaultLabel . " (" . $language->get('title|name') . ")";
				if($language->isDefault()) {
					$defaultField->label = $label;
					continue; 
				}
				$f = wire('modules')->get('InputfieldTextarea'); 		
				$f->attr('name', 'terms' . $language->id);
				$f->attr('value', isset($data["terms$language->id"]) ? $data["terms$language->id"] : ''); 
				$f->label = $label;
				$f->rows = 15; 
				$f->collapsed = Inputfield::collapsedBlank;
				$inputfields->add($f); 
			}
		}

		$termLimit = isset($data['termLimit']) ? (int) $data['termLimit'] : self::defaultTermLimit; 
		$maxLinks = isset($data['maxLinks']) ? (int) $data['maxLinks'] : self::defaultMaxLinks; 

		$f = wire('modules')->get('InputfieldInteger'); 
		$f->attr('name', 'termLimit'); 
		$f->attr('value', $termLimit); 
		$f->label = __('Maximum links per term'); 
		$f->required = true; 
		$f->description = __('Use this option to prevent the same term from being linked too many times in the same block of text.'); 
		$f->notes = __('Specify 1 or higher.');
		$f->columnWidth = 33; 
		$inputfields->add($f); 
			
		$f = wire('modules')->get('InputfieldInteger'); 
		$f->attr('name', 'maxLinks'); 
		$f->attr('value', $maxLinks);
		$f->label = __('Maximum terms to link'); 
		$f->description = __('Use this option to prevent too many terms from being linked in the same text.'); 
		$f->notes = __('Leave blank (or 0) for no maximum (recommended).'); 
		$f->columnWidth = 33; 
		$inputfields->add($f); 

		$f = wire('modules')->get('InputfieldInteger'); 
		$f->attr('name', 'distance'); 
		$f->attr('value', isset($data['distance']) ? (int) $data['distance'] : self::defaultDistance); 
		$f->label = __('Minimum link distance'); 
		$f->description = __('Use this option to prevent the same term from being linked more than once when it appears in close range.'); 
		$f->notes = __('Specify value in number of characters.'); 
		$f->columnWidth = 34; 
		$inputfields->add($f); 

		$f = wire('modules')->get('InputfieldText'); 
		$f->attr('name', 'allowTags'); 
		$f->attr('value', isset($data['allowTags']) ? $data['allowTags'] : self::defaultAllowTags); 
		$f->label = __('Allowed tags whitelist'); 
		$f->description = __('Enter a list of HTML tags (without brackets) that AutoLinks is allowed to generate links within, each separated by a space. When specified, links will only be generated if the terms appear somewhere within one of the given HTML tags. If left blank, terms will be linked within any HTML tags.'); // Allowed tags description
		$f->notes = __('Example: p li h3'); 
		$inputfields->add($f); 

		$fieldset = wire('modules')->get('InputfieldFieldset'); 
		$fieldset->label = __('Markup for links'); 
		$fieldset->collapsed = Inputfield::collapsedYes; 
		$fieldset->description = __('Variables: {href} is the URL to link and {text} is the anchor text.');

		$f = wire('modules')->get('InputfieldText'); 
		$f->attr('name', 'linkMarkup'); 
		$f->attr('value', !empty($data['linkMarkup']) ? $data['linkMarkup'] : self::defaultLinkMarkup); 
		$f->label = __('Link Markup (Internal Links)'); 
		$f->columnWidth = 50; 
		$f->description = __('Links that do NOT begin with a schema/protocol.'); 
		$fieldset->add($f); 

		$f = wire('modules')->get('InputfieldText'); 
		$f->attr('name', 'linkMarkupExt'); 
		$f->attr('value', !empty($data['linkMarkupExt']) ? $data['linkMarkupExt'] : self::defaultLinkMarkupExt); 
		$f->label = __('Link Markup (External Links)'); 
		$f->description = __('Links that DO begin with a schema/protocol like http://.'); 
		$f->columnWidth = 50; 
		$fieldset->add($f); 
		$inputfields->add($fieldset); 

		return $inputfields; 
	}
}
